//! The effect-browser **registry catalogue** extracted from `comp/effect_browser.rs`
//! (workspace size rule): the [`REGISTRY`] table of every addable effect across
//! the colour / spatial / generate / distort / stylize / keying stacks, each
//! tagged with its [`Category`], [`Stack`], `defaults()` index, and search
//! keywords. Pure data — the matcher / query logic in `effect_browser.rs`
//! (`filter`, `score_entry`) ranks against this table exactly as before, and it is
//! re-exported from `effect_browser` so `REGISTRY` / `EFFECT_REGISTRY` paths keep
//! resolving.

use super::effect_browser::{BrowserEntry, Category, Stack};

/// The full effect registry — every addable effect across both stacks. The
/// `default_index` of each entry is the slot in its stack's `defaults()` array,
/// so the registry and `Effect::defaults()` / `SpatialEffect::defaults()` must
/// stay in sync (the `registry_indices_match_defaults` test guards this).
pub const REGISTRY: &[BrowserEntry] = &[
    // --- Color correction (Effect::defaults() order) ------------------------
    BrowserEntry {
        name: "Tint",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 0,
        keywords: &["color", "duotone", "map", "black", "white"],
    },
    BrowserEntry {
        name: "Brightness & Contrast",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 1,
        keywords: &["bright", "contrast", "exposure"],
    },
    BrowserEntry {
        name: "Exposure",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 2,
        keywords: &["stops", "gamma", "brightness"],
    },
    BrowserEntry {
        name: "Levels",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 3,
        keywords: &[
            "gamma",
            "contrast",
            "histogram",
            "black point",
            "white point",
        ],
    },
    BrowserEntry {
        name: "Hue / Saturation",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 4,
        keywords: &["hsl", "saturate", "desaturate", "color", "vibrance"],
    },
    BrowserEntry {
        name: "Curves",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 5,
        keywords: &["tone", "contrast", "s-curve", "spline"],
    },
    BrowserEntry {
        name: "Color Balance",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 6,
        keywords: &["shadows", "midtones", "highlights", "grade", "tint"],
    },
    BrowserEntry {
        name: "Channel Mixer",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 7,
        keywords: &[
            "channel",
            "mixer",
            "swap",
            "rgb",
            "monochrome",
            "grayscale",
            "mix",
        ],
    },
    BrowserEntry {
        name: "Gradient Map",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 8,
        keywords: &[
            "gradient",
            "map",
            "luma",
            "ramp",
            "duotone",
            "grade",
            "color",
        ],
    },
    BrowserEntry {
        name: "Tritone",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 9,
        keywords: &[
            "tritone",
            "tint",
            "duotone",
            "three tone",
            "shadows",
            "midtones",
            "highlights",
            "grade",
        ],
    },
    BrowserEntry {
        name: "Motion Blur",
        category: Category::Color,
        stack: Stack::Color,
        default_index: 10,
        keywords: &["motion", "blur", "shutter", "temporal", "samples", "smear"],
    },
    // --- Spatial (SpatialEffect::defaults() order) --------------------------
    BrowserEntry {
        name: "Gaussian Blur",
        category: Category::Blur,
        stack: Stack::Spatial,
        default_index: 0,
        keywords: &["blur", "soften", "defocus", "smooth"],
    },
    BrowserEntry {
        name: "Box Blur",
        category: Category::Blur,
        stack: Stack::Spatial,
        default_index: 1,
        keywords: &["box", "blur", "average", "soften", "fast", "iterations"],
    },
    BrowserEntry {
        name: "Directional Blur",
        category: Category::Blur,
        stack: Stack::Spatial,
        default_index: 2,
        keywords: &["directional", "motion", "blur", "streak", "smear", "angle"],
    },
    BrowserEntry {
        name: "Radial Blur",
        category: Category::Blur,
        stack: Stack::Spatial,
        default_index: 3,
        keywords: &["radial", "blur", "spin", "zoom", "rotate", "circular", "twirl"],
    },
    BrowserEntry {
        name: "Drop Shadow",
        category: Category::Perspective,
        stack: Stack::Spatial,
        default_index: 4,
        keywords: &["shadow", "cast", "depth"],
    },
    BrowserEntry {
        name: "Glow",
        category: Category::Stylize,
        stack: Stack::Spatial,
        default_index: 5,
        keywords: &["bloom", "bright", "halo", "light"],
    },
    // --- Generate (GenerateEffect::defaults() order) ------------------------
    BrowserEntry {
        name: "Fractal Noise",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 0,
        keywords: &[
            "fractal",
            "noise",
            "turbulent",
            "perlin",
            "clouds",
            "smoke",
            "fbm",
            "evolution",
        ],
    },
    BrowserEntry {
        name: "Gradient Ramp",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 1,
        keywords: &[
            "ramp",
            "gradient",
            "linear",
            "radial",
            "fade",
            "blend",
            "color",
        ],
    },
    BrowserEntry {
        name: "Checkerboard",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 2,
        keywords: &["checker", "checkerboard", "chequer", "grid", "tile", "squares"],
    },
    BrowserEntry {
        name: "4-Color Gradient",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 3,
        keywords: &[
            "4 color",
            "four color",
            "gradient",
            "corner",
            "blend",
            "mesh",
        ],
    },
    BrowserEntry {
        name: "Grid",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 4,
        keywords: &["grid", "lines", "graph", "guides", "mesh", "checker"],
    },
    BrowserEntry {
        name: "Cell Pattern",
        category: Category::Generate,
        stack: Stack::Generate,
        default_index: 5,
        keywords: &[
            "cell",
            "cells",
            "voronoi",
            "worley",
            "cellular",
            "bubbles",
            "crystals",
            "plates",
            "organic",
            "web",
        ],
    },
    // --- Distort (DistortEffect::defaults() order) --------------------------
    BrowserEntry {
        name: "Corner Pin",
        category: Category::Distort,
        stack: Stack::Distort,
        default_index: 0,
        keywords: &[
            "corner",
            "pin",
            "perspective",
            "warp",
            "quad",
            "screen",
            "track",
        ],
    },
    BrowserEntry {
        name: "Transform",
        category: Category::Distort,
        stack: Stack::Distort,
        default_index: 1,
        keywords: &[
            "transform",
            "position",
            "scale",
            "rotate",
            "anchor",
            "skew",
            "move",
        ],
    },
    BrowserEntry {
        name: "Mirror",
        category: Category::Distort,
        stack: Stack::Distort,
        default_index: 2,
        keywords: &["mirror", "reflect", "flip", "symmetry", "kaleidoscope"],
    },
    BrowserEntry {
        name: "Polar Coordinates",
        category: Category::Distort,
        stack: Stack::Distort,
        default_index: 3,
        keywords: &[
            "polar",
            "coordinates",
            "radial",
            "tiny planet",
            "rect",
            "unwrap",
            "twirl",
        ],
    },
    BrowserEntry {
        name: "Displacement Map",
        category: Category::Distort,
        stack: Stack::Distort,
        default_index: 4,
        keywords: &[
            "displacement",
            "map",
            "warp",
            "distort",
            "ripple",
            "wave",
        ],
    },
    // --- Stylize (StylizeEffect::defaults() order) --------------------------
    BrowserEntry {
        name: "Find Edges",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 0,
        keywords: &[
            "find",
            "edges",
            "edge",
            "sobel",
            "outline",
            "ink",
            "contour",
            "detect",
        ],
    },
    BrowserEntry {
        name: "Mosaic",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 1,
        keywords: &[
            "mosaic",
            "pixelate",
            "pixelsize",
            "pixelize",
            "blocks",
            "censor",
            "tile",
        ],
    },
    BrowserEntry {
        name: "Stroke",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 2,
        keywords: &[
            "stroke",
            "outline",
            "border",
            "glow",
            "edge",
            "contour",
        ],
    },
    BrowserEntry {
        name: "Posterize",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 3,
        keywords: &["posterize", "quantize", "bands", "cel", "shade", "flat"],
    },
    BrowserEntry {
        name: "Invert",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 4,
        keywords: &["invert", "negative", "negate", "complement"],
    },
    BrowserEntry {
        name: "Threshold",
        category: Category::Stylize,
        stack: Stack::Stylize,
        default_index: 5,
        keywords: &["threshold", "black", "white", "bw", "binary", "cutoff"],
    },
    // --- Keying (KeyEffect::defaults() order) -------------------------------
    BrowserEntry {
        name: "Color Key",
        category: Category::Keying,
        stack: Stack::Keying,
        default_index: 0,
        keywords: &[
            "key",
            "color",
            "chroma",
            "green screen",
            "blue screen",
            "matte",
            "transparency",
            "tolerance",
        ],
    },
    BrowserEntry {
        name: "Luma Key",
        category: Category::Keying,
        stack: Stack::Keying,
        default_index: 1,
        keywords: &[
            "key",
            "luma",
            "luminance",
            "brightness",
            "threshold",
            "matte",
            "shadow",
            "highlight",
        ],
    },
    BrowserEntry {
        name: "Chroma Key",
        category: Category::Keying,
        stack: Stack::Keying,
        default_index: 2,
        keywords: &[
            "key",
            "chroma",
            "keylight",
            "green screen",
            "blue screen",
            "matte",
            "gain",
            "balance",
        ],
    },
    BrowserEntry {
        name: "Spill Suppression",
        category: Category::Keying,
        stack: Stack::Keying,
        default_index: 3,
        keywords: &[
            "spill",
            "suppress",
            "despill",
            "fringe",
            "green",
            "blue",
            "edge",
            "neutralise",
        ],
    },
    BrowserEntry {
        name: "Matte Choke",
        category: Category::Keying,
        stack: Stack::Keying,
        default_index: 4,
        keywords: &[
            "choke",
            "matte",
            "erode",
            "dilate",
            "shrink",
            "grow",
            "clip",
            "refine",
        ],
    },
];
