//! Icon enum for the Prism suite UI.

/// All available icons in the Prism UI icon set.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Icon {
    Cursor,
    Pen,
    Pencil,
    Brush,
    Eraser,
    Move,
    ZoomIn,
    ZoomOut,
    Eyedropper,
    Text,
    Rect,
    Ellipse,
    Line,
    Polygon,
    Lasso,
    Wand,
    Crop,
    Heal,
    Clone,
    Gradient,
    Fill,
    Shape,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Layers,
    Add,
    Remove,
    Trash,
    Check,
    Close,
    ChevronDown,
    ChevronRight,
    Play,
    Pause,
    Stop,
    Rewind,
    FastForward,
    Scissors,
    Link,
    Unlink,
    Grid,
    Settings,
    Export,
    Import,
    Undo,
    Redo,
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignTop,
    AlignMiddle,
    AlignBottom,
    DistributeH,
    DistributeV,
    Speaker,
    Mute,
    Volume,
    Camera,
    Film,
    Music,
    Waveform,
    Cut,
    Transition,
    ColorWheel,
    Mask,
    Adjustment,
    Histogram,
    Star,
    Heart,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
}

impl Icon {
    pub fn path(&self) -> &'static str {
        match self {
            Icon::Cursor       => "icons/cursor.svg",
            Icon::Pen          => "icons/pen.svg",
            Icon::Pencil       => "icons/pencil.svg",
            Icon::Brush        => "icons/brush.svg",
            Icon::Eraser       => "icons/eraser.svg",
            Icon::Move         => "icons/move.svg",
            Icon::ZoomIn       => "icons/zoom_in.svg",
            Icon::ZoomOut      => "icons/zoom_out.svg",
            Icon::Eyedropper   => "icons/eyedropper.svg",
            Icon::Text         => "icons/text.svg",
            Icon::Rect         => "icons/rect.svg",
            Icon::Ellipse      => "icons/ellipse.svg",
            Icon::Line         => "icons/line.svg",
            Icon::Polygon      => "icons/polygon.svg",
            Icon::Lasso        => "icons/lasso.svg",
            Icon::Wand         => "icons/wand.svg",
            Icon::Crop         => "icons/crop.svg",
            Icon::Heal         => "icons/heal.svg",
            Icon::Clone        => "icons/clone.svg",
            Icon::Gradient     => "icons/gradient.svg",
            Icon::Fill         => "icons/fill.svg",
            Icon::Shape        => "icons/shape.svg",
            Icon::Eye          => "icons/eye.svg",
            Icon::EyeOff       => "icons/eye_off.svg",
            Icon::Lock         => "icons/lock.svg",
            Icon::Unlock       => "icons/unlock.svg",
            Icon::Layers       => "icons/layers.svg",
            Icon::Add          => "icons/add.svg",
            Icon::Remove       => "icons/remove.svg",
            Icon::Trash        => "icons/trash.svg",
            Icon::Check        => "icons/check.svg",
            Icon::Close        => "icons/close.svg",
            Icon::ChevronDown  => "icons/chevron_down.svg",
            Icon::ChevronRight => "icons/chevron_right.svg",
            Icon::Play         => "icons/play.svg",
            Icon::Pause        => "icons/pause.svg",
            Icon::Stop         => "icons/stop.svg",
            Icon::Rewind       => "icons/rewind.svg",
            Icon::FastForward  => "icons/fast_forward.svg",
            Icon::Scissors     => "icons/scissors.svg",
            Icon::Link         => "icons/link.svg",
            Icon::Unlink       => "icons/unlink.svg",
            Icon::Grid         => "icons/grid.svg",
            Icon::Settings     => "icons/settings.svg",
            Icon::Export       => "icons/export.svg",
            Icon::Import       => "icons/import.svg",
            Icon::Undo         => "icons/undo.svg",
            Icon::Redo         => "icons/redo.svg",
            Icon::AlignLeft    => "icons/align_left.svg",
            Icon::AlignCenter  => "icons/align_center.svg",
            Icon::AlignRight   => "icons/align_right.svg",
            Icon::AlignTop     => "icons/align_top.svg",
            Icon::AlignMiddle  => "icons/align_middle.svg",
            Icon::AlignBottom  => "icons/align_bottom.svg",
            Icon::DistributeH  => "icons/distribute_h.svg",
            Icon::DistributeV  => "icons/distribute_v.svg",
            Icon::Speaker      => "icons/speaker.svg",
            Icon::Mute         => "icons/mute.svg",
            Icon::Volume       => "icons/volume.svg",
            Icon::Camera       => "icons/camera.svg",
            Icon::Film         => "icons/film.svg",
            Icon::Music        => "icons/music.svg",
            Icon::Waveform     => "icons/waveform.svg",
            Icon::Cut          => "icons/cut.svg",
            Icon::Transition   => "icons/transition.svg",
            Icon::ColorWheel   => "icons/color_wheel.svg",
            Icon::Mask         => "icons/mask.svg",
            Icon::Adjustment   => "icons/adjustment.svg",
            Icon::Histogram    => "icons/histogram.svg",
            Icon::Star         => "icons/star.svg",
            Icon::Heart        => "icons/heart.svg",
            Icon::ArrowUp      => "icons/arrow_up.svg",
            Icon::ArrowDown    => "icons/arrow_down.svg",
            Icon::ArrowLeft    => "icons/arrow_left.svg",
            Icon::ArrowRight   => "icons/arrow_right.svg",
        }
    }
}
